name: Hello  world pipeline
on:
  push:
    branches:
      - main
jobs:
  run-pipeline-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code Repository background
        uses: actions/checkout@v5
      - name: Test console output 
        run: echo "Pipeline is running sucessfully!!"
      - name: Compile Docker container image
        run: |
          echo "Starting Docker build process...."
          docker build -t my-first-app:latest .
         
